webcook_cms_i18n_language:
    resource: "@WebcookCmsI18nBundle/Controller/LanguageController.php"
    type:     rest
    prefix: /api

webcook_cms_i18n_translation:
    resource: "@WebcookCmsI18nBundle/Controller/TranslationController.php"
    type:     rest
    prefix: /api
